### ISSUE TITLE
iconfont-taro在RN端应用上的两个问题

### ISSUE THREAD

**Issue by aoarashi1988** [iconfont-cli/taro-iconfont-cli#12]
### 问题描述1
使用npx iconfont-taro脚本生成的/components/iconfont/rn/helper.d.ts在编译过程中报错
```
(node:1422) UnhandledPromiseRejectionWarning: SyntaxError: /Users/myproject/src/components/iconfont/rn/helper.d.ts: Unexpected token (2:25)
  1 | /* eslint-disable */
> 2 | export const getIconColor;
    |                          ^
  3 | 
    at Parser.pp$5.raise (/Users/aoarashi/Documents/project/eclass/eclass/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/aoarashi/Documents/project/eclass/eclass/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$1.parseVar (/Users/aoarashi/Documents/project/eclass/eclass/node_modules/babylon/lib/index.js:2342:12)
    at Parser.pp$1.parseVarStatement (/Users/aoarashi/Documents/project/eclass/eclass/node_modules/babylon/lib/index.js:2169:8)
    at Parser.pp$1.parseStatement (/Users/aoarashi/Documents/project/eclass/eclass/node_modules/babylon/lib/index.js:1861:19)
    at Parser.parseStatement (/Users/aoarashi/Documents/project/eclass/eclass/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseExportDeclaration (/Users/aoarashi/Documents/project/eclass/eclass/node_modules/babylon/lib/index.js:2666:15)
    at Parser.parseExportDeclaration (/Users/aoarashi/Documents/project/eclass/eclass/node_modules/babylon/lib/index.js:6038:22)
    at Parser.pp$1.parseExport (/Users/aoarashi/Documents/project/eclass/eclass/node_modules/babylon/lib/index.js:2654:29)
    at Parser.parseExport (/Users/aoarashi/Documents/project/eclass/eclass/node_modules/babylon/lib/index.js:6000:20)
(node:1422) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1422) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
而打开对应的文件，代码是这样的：
```
/* eslint-disable */

export const getIconColor: (color: string | string[] | undefined, index: number, defaultColor: string) => string;

```
报的符号错误并没有在原文件中找到，不知道怎么解决

### 问题描述2
从v1.6.3升级到1.7.0以后，所有图标文件都单独分出来了，而且文件开头有对React的引用
```
import React from 'react'
```
而Taro对所有组件重新编译的时候，同样会加一遍对React的引用，最终得到的是这样的：
```
import React from 'react';
/* eslint-disable */

import React from 'react';
import { Svg, Path } from 'react-native-svg';
import { getIconColor } from "./helper";

export const IconicBack = ({ size, color, ...rest }) => {
  return <Svg viewBox="0 0 1024 1024" width={size} height={size} {...rest}>
      <Path d="M620.6976 165.7088L319.3088 469.9136c-16.128 16.2816-16.128 42.496 0 58.3936L620.8 832.5888c16.128 16.2816 42.1632 16.2816 58.3168 0a41.728 41.728 0 0 0 0-58.7776L406.6304 499.1488 679.0912 224.512a41.728 41.728 0 0 0 0-58.8032A41.7792 41.7792 0 0 0 649.984 153.6a42.112 42.112 0 0 0-29.312 12.1088z" fill={getIconColor(color, 0, '#FFFFFF')} />
    </Svg>;
};

IconicBack.defaultProps = {
  size: 18
};

export default IconicBack;
```
也就是对React引用了两次，也会造成报错，现在我只能自己写个脚本把helper.d.ts删了，同时删除多余的React引用，希望这个能被解决

**Comment by fwh1990** [comment]
请问是仅在编译RN时出错吗？小程序中是否正常

**Comment by fwh1990** [comment]
知道问题了。一些新特性我还没发布，但是taro-iconfont-cli安装时，自动升级了一些依赖包。这两天我发布一个新版解决

**Comment by fwh1990** [comment]
我升级到 `taro-iconfont-cli@1.1.1`，请尝试是否修复。这几天请了陪产假，时间很挤，抱歉

**Comment by aoarashi1988** [comment]
问题解决，这个issue我关了
